export * from './modules/home'
export * from './modules/hot-details'
export * from './modules/category'
export * from './modules/goods-details'
export * from './modules/login-simple'
export * from './modules/profiles'
export * from './modules/address'
